name: CI
on:
  push:
    branches: [main, testing]

  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10.7', '9.2.5']
        cabal: ['3.6']
        os: [ubuntu-latest, macOS-latest]

    name: ghc-${{ matrix.ghc }} cabal-${{matrix.cabal}} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-v1-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-v1-

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: sdist
        run: |
          mkdir -p $HOME/sdist
          cabal sdist --output-dir $HOME/sdist

      - name: unpack
        run: |
          rm -rf $GITHUB_WORKSPACE/*
          find $HOME/sdist -maxdepth 1 -type f -name '*.tar.gz' -exec tar -C $GITHUB_WORKSPACE -xzvf {} --strip 1 \;

      - name: build
        run: cabal build --upgrade-dependencies --enable-tests --enable-benchmarks

      - name: test
        run: cabal test --test-show-details=always

      - name: check
        run: cabal check

      - name: haddock
        run: cabal haddock
